version: "3.9"
services:
  # This service name will be also used as hostname for MONGODB
  db:
    image: mongo:5.0.5
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data: /data/db
    restart: always
  
  backend:
    build:
      context: ./
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - ${QR_CODE_API_UVICORN_PORT}:${QR_CODE_API_UVICORN_PORT}
    restart: always

volumes:
  mongodb-data:
